server:
  port: 8989

spring:
  cloud:
    gateway:
      routes:
        - id: notes
          uri: http://localhost:8081/
          predicates:
            - Path=/notes/**
        - id: reminder
          uri: http://localhost:8082/
          predicates:
            - Path=/reminders/**
